### PR TITLE
Fixed loadUserIdFromUsername function by changing get request to post…

### PR DESCRIPTION
**Pull request by frius94**
Fixed loadUserIdFromUsername function by changing get request to post request with credentials.<br>
The function used to have an issue finding the username without the credentials with the GET request.<br>
The new POST request takes the credentials and receives as a response which includes the userId.<br>
You can test it with `medal-downloader --username your_username --password your_password`

### CODE REVIEW

**Comment by noeRls** [comment]
I think there is a way to load the user id without the password using `https://medal.tv/api/users?username=pingui34`. I will try it out this weekend.

**Comment by noeRls** [comment]
Hey @frius94 thanks for your contribution!

I am trying to reproduce the error you're trying to fix, what's your username?

I don't like that users have to enter their password to download their videos, it can lead to security issues. That's why I am looking at an other way of doing it. If there is no other way I will merge your cl :)

**Comment by frius94** [comment]
Hi @noeRls .
My username on Medal is: umut94

**Comment by noeRls** [comment]
Hey I can't reproduce the error.

From what I understand you have an error: "Invalid username: umut94" displayed, weather you're using your password or not right?

I have update the package with an other way of fetching the userId that doesn't involve regex parsing with "https://medal.tv/api/users?username=pingui34" endpoint, can you take a look if you still have the error?

**Comment by frius94** [comment]
I tested your changes. It works with and without password, which is awesome. But using the --url parameter didn't work for me.
How are you supposed to use the url?
Like this?: https://medal.tv/api/users?username=pingui34
Or this: https://medal.tv/users/pingui34

**Comment by noeRls** [comment]
Great to hear that it works now!

The parameter for the --url should be something like: https://medal.tv/users/pingui34
This doesn't work for you?

**Comment by noeRls** [comment]
closing due to inactivity, feel free to re-open

**Pull request closed without merging**
